spring:
  application:
    name: spring-cloud-eureka-client

server:
  port: 7777

eureka:
  client:
    registerWithEureka: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http:192.168.3.60:8888/eureka/
    fetch-registry: true

  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true