server:
  port: 8765
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  instance:
    hostname: eureka1
  client:
   registerWithEureka: false
   fetch-registry: false
   service-url:
    defaultZone: http://eureka1:8765/eureka/
