spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
      - id: header_route
        uri: http://example.org
        predicates:
        - Header=X-Request-Id, \d+


server:
  port: 9999