spring:
  application:
    name: "phone-show-admin"
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true

server:
  port: 7774
  servlet:
    context-path: "/admin"

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://127.0.0.1:8888/eureka/"

  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
mybatis:
  config-location: "classpath:mybatis-config.xml"


